import { cn } from '@/lib/utils';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/Toaster';
import Navbar from '@/components/Navbar';
import Providers from '@/components/Providers';
import { authOptions, getAuthSession } from '@/lib/auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getAuthSession();

  return (
    <html
      lang='en'
      className={cn(
        'bg-white text-slate-900 antialiased light',
        inter.className
      )}
    >
      <body className='grid min-h-screen pt-4 antialiased md:grid-cols-sidebar bg-slate-50'>
        <Providers>
          <Navbar session={session} />
          <div className='grid grid-cols-3'>{children}</div>
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
